apiVersion: batch/v1
kind: Job
metadata:
  name: seeding
spec:
  template:
    spec:
      containers: 
      - name: seeding
        image: nyuappsec/assign3-db:v0
        command: ["/bin/bash"]
        args: ["-c", "mysql --user=root --password=${MYSQL_ROOT_PASSWORD} --database=${MYSQL_DATABASE} --host=mysql-service -f < /docker-entrypoint-initdb.d/seeding.sql"]
        env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: password

            - name: MYSQL_DB
              value: GiftcardSiteDB

      restartPolicy: Never

